name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    name: MacOS 12
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["14.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Print Swift version
        run: swift --version
      - name: Run test
        run: make test-swift

  linux:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: make test-linux
